### ISSUE TITLE
ga.ua 값과 adsense.client 값을 수정해 주세요.

### ISSUE THREAD

**Issue by johngrib** [ji-junhyuk/ji-junhyuk.github.io#1]
안녕하세요. google analytics 값과 google adsense 값이 제 블로그에서 사용하고 있는 값과 같은 것으로 보입니다.
이 값을 수정해주셔야 선생님 블로그의 ga 기능을 제대로 사용하실 수 있을 것 같아요.

https://github.com/ji-junhyuk/ji-junhyuk.github.io/blob/c11659839758f5b853b92971674ec2f8694e4e30/_config.yml#L48-L52

**Comment by ji-junhyuk** [comment]
감사합니다 종립님♥♥♥
